In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
X=digits.data
Y=digits.target
X,Y

(array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 array([0, 1, 2, ..., 8, 9, 8]))

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [5]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

C:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [6]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9833333333333333

In [7]:
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9666666666666667

In [8]:
dt=DecisionTreeClassifier()
dt.fit(X_train,Y_train)
dt.score(X_test,Y_test)

0.8666666666666667

In [9]:
#K fold

In [10]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index )

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [13]:
get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test)

C:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [14]:
get_score(SVC(),X_train,X_test,Y_train,Y_test)

0.9833333333333333

In [15]:
get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test)

0.9740740740740741

In [16]:
get_score(DecisionTreeClassifier(),X_train,X_test,Y_train,Y_test)

0.8555555555555555

In [17]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [18]:
scores_lr=[]
scores_svm=[]
scores_rf=[]
scores_dt=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,Y_train,Y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(),X_train,X_test,Y_train,Y_test))

C:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [19]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [20]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [21]:
scores_rf

[0.9148580968280468, 0.9432387312186978, 0.9165275459098498]

In [22]:
scores_dt

[0.7696160267111853, 0.8046744574290484, 0.7729549248747913]

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [25]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [26]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.925     , 0.91388889, 0.9637883 , 0.97771588, 0.91922006])

In [27]:
cross_val_score(DecisionTreeClassifier(),digits.data,digits.target)

array([0.77222222, 0.71388889, 0.78551532, 0.82451253, 0.78272981])

In [28]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91388889, 0.90277778, 0.95821727, 0.96935933, 0.92200557])

In [29]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.86111111, 0.82222222, 0.91922006, 0.91364903, 0.85793872])

In [30]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target)

array([0.89166667, 0.84722222, 0.92200557, 0.93036212, 0.88300836])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.94166667, 0.91388889, 0.95821727, 0.97771588, 0.92200557])